### Add product to catalog

POST https://localhost/products
Content-Type: application/x-www-form-urlencoded

name=Example product 44&price=444

### Edit product in catalog

POST https://localhost/product/edit
Content-Type: application/x-www-form-urlencoded

id=544b61bf-6a60-413f-a83d-1aaf3f3f75ff&name=Example product 5555&price=55555

### Remove product from catalog

DELETE https://localhost/products/408d31bc-69fa-46a8-aee8-0c3e72bba6b6

### List products

GET https://localhost/products

### Create cart

POST https://localhost/cart

> {% client.global.set("cart_id", response.body.cart_id) %}

### Add product to cart

PUT https://localhost/cart/{{cart_id}}/544b61bf-6a60-413f-a83d-1aaf3f3f75ff

### Remove product from cart

DELETE https://localhost/cart/{{cart_id}}/544b61bf-6a60-413f-a83d-1aaf3f3f75ff

### Show cart

GET https://localhost/cart/{{cart_id}}
