<?php

namespace ContainerCRTHBeN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3tJvfBCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3tJvfBC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3tJvfBC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cart' => ['privates', '.errored..service_locator.3tJvfBC.App\\Entity\\Cart', NULL, 'Cannot autowire service ".service_locator.3tJvfBC": it references class "App\\Entity\\Cart" but no such service exists.'],
        ], [
            'cart' => 'App\\Entity\\Cart',
        ]);
    }
}
