<?php

namespace ContainerCRTHBeN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_EJCE4C1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.EJCE4C1' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Messenger/RemoveProductFromCatalogHandler.php';

        return $container->privates['.messenger.handler_descriptor.EJCE4C1'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Messenger\RemoveProductFromCatalogHandler(($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService'))), []);
    }
}
