<?php

namespace ContainerCRTHBeN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Catalog\AddController' shared autowired service.
     *
     * @return \App\Controller\Catalog\AddController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Messenger/MessageBusAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Messenger/MessageBusTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Catalog/AddController.php';
        include_once \dirname(__DIR__, 4).'/src/ResponseBuilder/ErrorBuilder.php';

        $container->services['App\\Controller\\Catalog\\AddController'] = $instance = new \App\Controller\Catalog\AddController(($container->privates['App\\ResponseBuilder\\ErrorBuilder'] ?? ($container->privates['App\\ResponseBuilder\\ErrorBuilder'] = new \App\ResponseBuilder\ErrorBuilder())));

        $instance->setMessageBus(($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')));
        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\Catalog\\AddController', $container));

        return $instance;
    }
}
