<?php

namespace ContainerCRTHBeN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Cart\CreateController' shared autowired service.
     *
     * @return \App\Controller\Cart\CreateController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/HandleTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Cart/CreateController.php';

        $container->services['App\\Controller\\Cart\\CreateController'] = $instance = new \App\Controller\Cart\CreateController(($container->privates['App\\Repository\\CartRepository'] ?? $container->load('getCartRepositoryService')), ($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\Cart\\CreateController', $container));

        return $instance;
    }
}
