<?php

namespace ContainerJEQksBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AJypU1SService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.AJypU1S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AJypU1S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cart' => ['privates', '.errored..service_locator.AJypU1S.App\\Entity\\Cart', NULL, 'Cannot autowire service ".service_locator.AJypU1S": it references class "App\\Entity\\Cart" but no such service exists.'],
        ], [
            'cart' => 'App\\Entity\\Cart',
        ]);
    }
}
