<?php

namespace ContainerJEQksBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddProductToCartHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Messenger\AddProductToCartHandler' shared autowired service.
     *
     * @return \App\Messenger\AddProductToCartHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Messenger/AddProductToCartHandler.php';

        return $container->privates['App\\Messenger\\AddProductToCartHandler'] = new \App\Messenger\AddProductToCartHandler(($container->privates['App\\Repository\\CartRepository'] ?? $container->load('getCartRepositoryService')));
    }
}
