<?php

namespace ContainerJEQksBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddProductToCatalogHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Messenger\AddProductToCatalogHandler' shared autowired service.
     *
     * @return \App\Messenger\AddProductToCatalogHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Messenger/AddProductToCatalogHandler.php';

        return $container->privates['App\\Messenger\\AddProductToCatalogHandler'] = new \App\Messenger\AddProductToCatalogHandler(($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')));
    }
}
