<?php

namespace ContainerJEQksBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartBuilderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\ResponseBuilder\CartBuilder' shared autowired service.
     *
     * @return \App\ResponseBuilder\CartBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/ResponseBuilder/CartBuilder.php';

        return $container->privates['App\\ResponseBuilder\\CartBuilder'] = new \App\ResponseBuilder\CartBuilder();
    }
}
