<?php

namespace ContainerJEQksBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_MessengerDebugService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'console.command.messenger_debug' shared service.
     *
     * @return \Symfony\Component\Messenger\Command\DebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Command/DebugCommand.php';

        $container->privates['console.command.messenger_debug'] = $instance = new \Symfony\Component\Messenger\Command\DebugCommand(['messenger.bus.default' => ['App\\Messenger\\AddProductToCart' => [0 => [0 => 'App\\Messenger\\AddProductToCartHandler', 1 => []]], 'App\\Messenger\\AddProductToCatalog' => [0 => [0 => 'App\\Messenger\\AddProductToCatalogHandler', 1 => []]], 'App\\Messenger\\CreateCart' => [0 => [0 => 'App\\Messenger\\CreateCartHandler', 1 => []]], 'App\\Messenger\\RemoveProductFromCart' => [0 => [0 => 'App\\Messenger\\RemoveProductFromCartHandler', 1 => []]], 'App\\Messenger\\RemoveProductFromCatalog' => [0 => [0 => 'App\\Messenger\\RemoveProductFromCatalogHandler', 1 => []]]]]);

        $instance->setName('debug:messenger');
        $instance->setDescription('List messages you can dispatch using the message buses');

        return $instance;
    }
}
