<?php

namespace ContainerJEQksBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getErrorBuilderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\ResponseBuilder\ErrorBuilder' shared autowired service.
     *
     * @return \App\ResponseBuilder\ErrorBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/ResponseBuilder/ErrorBuilder.php';

        return $container->privates['App\\ResponseBuilder\\ErrorBuilder'] = new \App\ResponseBuilder\ErrorBuilder();
    }
}
