<?php

namespace ContainerJEQksBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExceptionListenerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Listener\ExceptionListener' shared autowired service.
     *
     * @return \App\Listener\ExceptionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Listener/ExceptionListener.php';
        include_once \dirname(__DIR__, 4).'/src/ResponseBuilder/ErrorBuilder.php';

        return $container->privates['App\\Listener\\ExceptionListener'] = new \App\Listener\ExceptionListener(($container->privates['App\\ResponseBuilder\\ErrorBuilder'] ?? ($container->privates['App\\ResponseBuilder\\ErrorBuilder'] = new \App\ResponseBuilder\ErrorBuilder())));
    }
}
