<?php

namespace ContainerJEQksBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Catalog\ListController' shared autowired service.
     *
     * @return \App\Controller\Catalog\ListController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Catalog/ListController.php';

        $container->services['App\\Controller\\Catalog\\ListController'] = $instance = new \App\Controller\Catalog\ListController(($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')), ($container->privates['App\\ResponseBuilder\\ProductListBuilder'] ?? $container->load('getProductListBuilderService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\Catalog\\ListController', $container));

        return $instance;
    }
}
