<?php

namespace ContainerJEQksBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Bus_Default_Messenger_HandlersLocatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'messenger.bus.default.messenger.handlers_locator' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlersLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocator.php';

        return $container->privates['messenger.bus.default.messenger.handlers_locator'] = new \Symfony\Component\Messenger\Handler\HandlersLocator(['App\\Messenger\\AddProductToCart' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.oJRXavk'] ?? $container->load('get_Messenger_HandlerDescriptor_OJRXavkService'));
        }, 1), 'App\\Messenger\\AddProductToCatalog' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.KhWhntg'] ?? $container->load('get_Messenger_HandlerDescriptor_KhWhntgService'));
        }, 1), 'App\\Messenger\\CreateCart' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.XiLdWcV'] ?? $container->load('get_Messenger_HandlerDescriptor_XiLdWcVService'));
        }, 1), 'App\\Messenger\\RemoveProductFromCart' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.pGHZcSn'] ?? $container->load('get_Messenger_HandlerDescriptor_PGHZcSnService'));
        }, 1), 'App\\Messenger\\RemoveProductFromCatalog' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.EJCE4C1'] ?? $container->load('get_Messenger_HandlerDescriptor_EJCE4C1Service'));
        }, 1)]);
    }
}
