<?php

namespace ContainerJEQksBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductListBuilderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\ResponseBuilder\ProductListBuilder' shared autowired service.
     *
     * @return \App\ResponseBuilder\ProductListBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/ResponseBuilder/ProductListBuilder.php';

        return $container->privates['App\\ResponseBuilder\\ProductListBuilder'] = new \App\ResponseBuilder\ProductListBuilder(($container->services['router'] ?? $container->getRouterService()));
    }
}
