<?php

namespace ContainerJEQksBG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveProductFromCatalogHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Messenger\RemoveProductFromCatalogHandler' shared autowired service.
     *
     * @return \App\Messenger\RemoveProductFromCatalogHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Messenger/RemoveProductFromCatalogHandler.php';

        return $container->privates['App\\Messenger\\RemoveProductFromCatalogHandler'] = new \App\Messenger\RemoveProductFromCatalogHandler(($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')));
    }
}
