<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJEQksBG\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJEQksBG/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJEQksBG.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJEQksBG\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerJEQksBG\App_KernelTestDebugContainer([
    'container.build_hash' => 'JEQksBG',
    'container.build_id' => 'f6b7dfa5',
    'container.build_time' => 1717684372,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJEQksBG');
