<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'cart-add-product' => [['cart', 'product'], ['_controller' => 'App\\Controller\\Cart\\AddProductController'], [], [['variable', '/', '[^/]++', 'product', true], ['variable', '/', '[^/]++', 'cart', true], ['text', '/cart']], [], [], []],
    'cart-create' => [[], ['_controller' => 'App\\Controller\\Cart\\CreateController'], [], [['text', '/cart']], [], [], []],
    'cart-remove-product' => [['cart', 'product'], ['_controller' => 'App\\Controller\\Cart\\RemoveProductController'], [], [['variable', '/', '[^/]++', 'product', true], ['variable', '/', '[^/]++', 'cart', true], ['text', '/cart']], [], [], []],
    'cart-show' => [['cart'], ['_controller' => 'App\\Controller\\Cart\\ShowCartController'], [], [['variable', '/', '[^/]++', 'cart', true], ['text', '/cart']], [], [], []],
    'product-add' => [[], ['_controller' => 'App\\Controller\\Catalog\\AddController'], [], [['text', '/products']], [], [], []],
    'product-edit' => [[], ['_controller' => 'App\\Controller\\Catalog\\EditController'], [], [['text', '/product/edit']], [], [], []],
    'product-list' => [[], ['_controller' => 'App\\Controller\\Catalog\\ListController'], [], [['text', '/products']], [], [], []],
    'product-delete' => [['product'], ['_controller' => 'App\\Controller\\Catalog\\RemoveController'], [], [['variable', '/', '[^/]++', 'product', true], ['text', '/products']], [], [], []],
];
